# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e716955990ba2eb0c07793100c93ee8bc85483ac208cc0fc750ae8625ff1c80ba13b73820fddd47946e566db5275871d5b050d940f887dcc22cf8ef6d74a2910

test:
  secret_key_base: 89890e2a6aafc995127b36ab0d3e557a207ec241de6b6d32cc8f691bcb6dca31632ccdef2d1d5ff3ccebe6b2a0ed152b5264110a0e2d12c8c0abffa620429c41

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
